### ISSUE TITLE
Aperçu ne fonctionne pas correctement

### ISSUE THREAD

**Issue by adeljebali** [CCDMD/netquizweb#3]
J’ai installé la dernière version de netquiz Web sur un serveur et j’ai commencé à travailler pour créer des exercices. Tout fonctionne bien à part le bouton « Aperçu », puisque tout semble brisé et même le texte ne s'affiche pas, à chaque fois. Quand je corrige les permissions sur les fichiers pour les rendre exécutables, tout baigne. Je ne peux cependant pas toujours le faire parce que c'est contre-productif. L’hébergeur ne trouve pas le problème. Pourriez-vous SVP m’aider?

**Comment by RichardDumoulin** [comment]
Bonjour!

1) Dans le fichier defaults.inc.php, cherchez les lignes suivantes : 

// ** Permet d'activer le changement de permissions pour les aperçus.  Valeurs possibles : 0 ou 1 ** //
define('ACTIVER_CHANGEMENT_PERMISSIONS_FICHIERS_APERCUS', "0");

2) Modifier la valeur de "0" à "1" 

3) Essayez à nouveau?

Ceci active le changement de permissions des aperçus afin qu'il soit automatique.

**Comment by adeljebali** [comment]
Merci. Ça fonctionne maintenant, mais en haut de ma page Netquiz, j'ai cette ligne qui se répète des dizaines de fois : Strict Standards: Non-static method Fichiers::chmodRecursif() should not be called statically, assuming $this from incompatible context in /home/coursweb/public_html/nqw/ressources/classes/outils/Fichiers.php on line 505

**Comment by RichardDumoulin** [comment]
L'application a été développée sur des versions ultérieures de PHP/Apache/MySQL et ce message d'avertissement n'était pas visible.

Pour corriger ce message, essayez ceci : 

1) Localiser le fichier /ressources/classes/outils/Fichiers.php

2) Trouvez la ligne (480) : 

function chmodRecursif($repertoire, $permFichier=0644, $permRep=0775) {

3) Mettez devant le mot static comme ceci : 

static function chmodRecursif($repertoire, $permFichier=0644, $permRep=0775) {

Est-ce que ça corrige le problème?

**Comment by adeljebali** [comment]
Grand grand merci. Tout est nickel maintenant. J'apprécie votre aire super rapide :)

**Comment by RichardDumoulin** [comment]
Aucun problème! J'espère que l'application pourra vous aider :)

A+

**Comment by adeljebali** [comment]
Oui, elle est très utile pour mon projet éducatif.

**Comment by soutien-CCDMD** [comment]
Thanx Richard!

**Comment by ghost** [comment]
Merci beaucoup, cela a fonctionné pour moi aussi, je cherchais du côté des htacess (mon répertoire nqw est un sous-répertoire de Drupal).

Stéphane
