### ISSUE TITLE
Erreur 403

### ISSUE THREAD

**Issue by adeljebali** [CCDMD/netquizweb#5]
Bonjour,

Ce matin, je commence à avoir cette erreur chaque fois que je veux ajouter des exerices à mon questionnaire : 

Forbidden

You don't have permission to access /nqw/app/questionnaires.php on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

La dernière fois que j'ai travaillé sur Netquiz Web je n'avais pas ce message. Merci de votre aide.

**Comment by RichardDumoulin** [comment]
Bonjour!

Ce message indique que le serveur web ne dispose pas des droits pour lire ou exécuter le programme questionnaires.php.  C'est un problème de permissions entre le serveur web et les fichiers de l'application.

De plus, vous avez aussi une erreur de permission au niveau du serveur web lorsqu'il tente de lire la page d'erreur par défaut.

Je vous recommande de vérifier dans les journaux du serveur web afin d'obtenir plus d'informations sur l'erreur.

Ce type d'erreur peut se produire pour plusieurs raisons dont : 
- Mise à niveau du serveur web
- Problème de configuration pour le host (domaine) dans Apache ou le serveur que vous utilisez
- Problème avec un fichier .htaccess

A+

Richard

**Comment by adeljebali** [comment]
Merci. Je dois donc vérifier auprès de mon hébergeur?

**Comment by RichardDumoulin** [comment]
Oui, si possible, demander leur un extrait du journal des erreurs du serveur web au moment où le problème est survenu. Idéalement, leur mentionner la date et l'heure approximative ainsi que le type d'erreur.

**Comment by adeljebali** [comment]
Merci. Problème réglé avec l'hébergeur : "I've disabled mod_security rule which caused the issue."

Bonne journée.

**Comment by RichardDumoulin** [comment]
Excellent! Merci pour le retour!

Bonne journée! :)
