### ISSUE TITLE
Erreur 018 et log vide à l'installation

### ISSUE THREAD

**Issue by musitoph** [CCDMD/netquizweb#6]
Bonjour.
J'ai essayé d'installer l'application sur mon espace web dans un sous-domaine créé pour l'occasion et au lancement de l'installation, je tombe directement sur une erreur 018 (premier try-catch du fichier d'installation) et le log ne contient aucune autre indication (il est vide, et pourtant, j'ai, il me semble, géré le droits d'écriture).
Merci d'avance pour votre retour éventuel !

**Comment by RichardDumoulin** [comment]
Bonjour!

Vous pouvez activer la journalisation plus "détaillée" en modifiant cette valeur dans le fichier defaults.inc.php : 

define('JOURNALISATION_NIVEAU', '5');

La valeur de '5' affichera tous les détails.  Par la suite tentez à nouveau le lancement de l'installation.

Vérifiez ensuite dans /ressources/journaux/ pour voir le problème.

Bonne journée!

**Comment by musitoph** [comment]
Merci pour votre réponse.
Effectivement, une fois la ligne changée, le log s'écrit et je constate que mon problème rejoint celui indiqué par sebseb01 (problème #2 ).
En fait, si je comprends bien, mon problème vient du fait que ma base de données contient déjà des tables (je n'ai pas d'autre choix, car j'ai la contrainte de ne pouvoir utiliser qu'une seule base, base que j'utilise déjà pour plusieurs Wordpress et également pour Owncloud).
A la limite, j'essaierai de préparer la base manuellement avant de retenter l'installation.
Merci encore !

**Comment by RichardDumoulin** [comment]
Bonjour!

Si vous êtes à l'aise avec le code PHP, vous pourriez désactiver la validation dans install.php : 

if ($tablesTotal == INSTALLATION_NOMBRE_TABLES) {
....

}

L'application devrait fonctionner par la suite, même s'il y a d'autres tables dans la BD.

**Comment by musitoph** [comment]
Bonjour.
Merci pour le conseil !

**Comment by RichardDumoulin** [comment]
SVP laissez-moi savoir si ça fonctionne?

**Comment by musitoph** [comment]
Bien sûr ! Ceci dit, ce sera sans doute dans le courant du week-end prochain (je fais ça dans mon temps libre).

**Comment by musitoph** [comment]
Bonjour.

J'ai finalement effectué les actions suivantes : 
- J'ai installé les tables manuellement dans ma base de données à l'aide du contenu du fichier .sql. Aucun souci à partir du moment où il n'y avait aucun conflit au niveau du nom des tables déjà présentes dans ma base.
- Comme vous me l'avez suggéré, j'ai commenté dans le fichier install.php la condition if ($tablesTotal == INSTALLATION_NOMBRE_TABLES) { ... } et le else suivant.

Après ça, l'installation se déroule sans aucun problème et l'application fonctionne très bien. Je pense qu'il est donc tout à fait possible pour l'application de partager une base avec d'autres applications. Ce qui serait la cerise sur le gâteau, peut-être pour une prochaine version, serait de pouvoir préfixer le nom des tables pour qu'elles soient regroupées dans la base (cela faciliterait certaines opérations de maintenance), mais ce n'est absolument pas obligatoire.

Merci beaucoup pour votre aide et pour cette application très complète et intuitive.

P.S. : dans mes premiers tests d'utilisation, j'ai eu des soucis d'affichage pour les aperçus et la version publiée des questionnaires, mais cela a été vite réglé par l'édition des droits des fichiers et des dossiers concernés.

**Comment by RichardDumoulin** [comment]
Pour les problèmes de permissions des aperçus, j'ai ajouté une option qui permet de changer les permissions automatiquement après la création de l'aperçu.

Voir la ligne 24 dans defaults.inc.php : 

// *\* Permet d'activer le changement de permissions pour les aperçus.  Valeurs possibles : 0 ou 1 *\* //
define('ACTIVER_CHANGEMENT_PERMISSIONS_FICHIERS_APERCUS', "0");

Il suffit de le mettre à 1 pour activer cette mécanique.

A+ et merci pour le suivi! :)
